/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jdbc_test;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.HashMap;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) throws SQLException {

        // String sql = "CREATE TABLE ACCOUNT (id int, username varchar(255), password varchar(255))";
        // String insertSql = "insert into account values(3,'degan3', 'pass3')";
        // String updateSql = "update account set username='de' where id=2";
        // exeSql(insertSql);
        String sSql = "select * from account";
        selectSql(sSql);
    }

    private static void exeSql(String sql) throws SQLException {

        // try with resource
        try(Connection connection = getConnection()) {

            try(PreparedStatement statement = connection.prepareStatement(sql)) {
                statement.execute();
            }
        }

    }

    private static void selectSql(String sql) throws SQLException {

        ResultSet rs = null;

        // try with resource
        try(Connection connection = getConnection()) {

            try(PreparedStatement statement = connection.prepareStatement(sql)) {
                rs = statement.executeQuery();

                while(rs.next()){     
                    String id = rs.getString("id");
                    String username = rs.getString("username");
                    String password = rs.getString("password");

                    System.out.printf("@@@ id: %s username : %s password : %s \n", id, username, password);
                }
            }
        }
    }

    private static Connection getConnection() throws SQLException {
        String url = "jdbc:postgresql://localhost:5432/springdata";
        String username = "degan";
        String password = "pass";

        return DriverManager.getConnection(url, username, password);
    }
}
