/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jdbc_test;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) throws SQLException {
        // System.out.println(new App().getGreeting());
        String url = "jdbc:postgresql://localhost:5432/springdata";
        String username = "degan";
        String password = "pass";

        // try with resource
        try(Connection connection = DriverManager.getConnection(url, username, password)) {
            System.out.println("Connection create : "+connection);

            String sql = "CREATE TABLE ACCOUNT (id int, username varchar(255), password varchar(255))";
            try(PreparedStatement statement = connection.prepareStatement(sql)) {
                statement.execute();
            }

            String insertSql = "insert into account values(1,'degan', 'pass')";
            try(PreparedStatement statement = connection.prepareStatement(insertSql)) {
                statement.execute();
            }
        }
    }
}
